In [7]:
import pandas as pd
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent))

def read_csv_with_user_agent(url) -> pd.DataFrame:
	return pd.read_csv(url, storage_options={
				"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
			})

In [ ]:
dat = read_csv_with_user_agent("https://rplumber.ilo.org/data/indicator?id=EMP_TEMP_SEX_OC2_NB_A&timefrom=2015&timeto=2025&type=label&format=.csv")
dat

/tmp/ipykernel_34771/2105037987.py:8: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  dat = pd.read_csv(

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: Total",2021,7679.474,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 02 - Non-...",2021,209.728,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 11 - Chie...",2021,7.876,Unreliable,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 12 - Admi...",2021,89.945,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 13 - Prod...",2021,23.102,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
...,...,...,...,...,...,...,...,...,...,...,...
116207,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 92 - Agri...",2019,94.305,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
116208,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 93 - Labo...",2019,13.376,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
116209,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 94 - Food...",2019,5.392,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
116210,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 95 - Stre...",2019,84.010,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
116211,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 96 - Refu...",2019,35.695,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...

In [8]:
dat = read_csv_with_user_agent("https://rplumber.ilo.org/data/indicator?id=EMP_TEMP_SEX_OC2_NB_A&timefrom=2015&timeto=2025&type=label&format=.csv")
dat

/tmp/ipykernel_34771/3488283287.py:8: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(url, storage_options={

,ref_area.label,source.label,indicator.label,sex.label,classif1.label,time,obs_value,obs_status.label,note_classif.label,note_indicator.label,note_source.label
0,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: Total",2021,7679.474,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
1,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 02 - Non-...",2021,209.728,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
2,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 11 - Chie...",2021,7.876,Unreliable,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
3,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 12 - Admi...",2021,89.945,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
4,Afghanistan,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Total,"Occupation (ISCO-08), 2 digit level: 13 - Prod...",2021,23.102,NaN,NaN,NaN,Repository: ILO-STATISTICS - Micro data proces...
...,...,...,...,...,...,...,...,...,...,...,...
116207,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 92 - Agri...",2019,94.305,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
116208,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 93 - Labo...",2019,13.376,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
116209,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 94 - Food...",2019,5.392,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
116210,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 95 - Stre...",2019,84.010,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...
116211,Zimbabwe,LFS - Labour Force Survey,Employment by sex and occupation - ISCO level ...,Female,"Occupation (ISCO-08), 2 digit level: 96 - Refu...",2019,35.695,Break in series,NaN,Break in series: Methodology revised,Repository: ILO-STATISTICS - Micro data proces...

In [10]:
dat["classif1.label"].value_counts()

classif1.label
Occupation (ISCO-08), 2 digit level: Total                                                            2679
Occupation (ISCO-08), 2 digit level: 51 - Personal service workers                                    2671
Occupation (ISCO-08), 2 digit level: 52 - Sales workers                                               2670
Occupation (ISCO-08), 2 digit level: 61 - Market-oriented skilled agricultural workers                2670
Occupation (ISCO-08), 2 digit level: 23 - Teaching professionals                                      2669
                                                                                                      ...
Occupation (ISCO-88), 2 digit level: 31 - Physical and engineering science associate professionals     102
Occupation (ISCO-88), 2 digit level: Not elsewhere classified                                          102
Occupation (ISCO-88), 2 digit level: 11 - Legislators and senior officials                              99
Occupation (ISCO-88), 2 digit level: 62 - Subsistence agricultural and fishery workers                  73
Occupation (ISCO-88), 2 digit level: 01 - Armed forces                                                  66
Name: count, Length: 75, dtype: int64